drop table if exists bookmarks;

create table bookmarks (

  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   title TEXT NOT NULL,
   description TEXT,
   url TEXT NOT NULL,
   rating INTEGER

);


insert into bookmarks(title,description,url,rating)
values
('Amazon','buy almost anything','https://amazon.com.com','5'),
('Thinkful','where i became a developer','https://www.thinkful.com','5'),
('Bing','not really that popular', 'https://bing.com','1'),
('Twitch','stream games here','https://twitch.com','4'),
('Youtube','watch content from everyone','https://youtube.com','3'),
('Netflix','Netflix and chill','https://netflix.com','3'),
('Instagram','the coolest app on the net','https://instagram.com','5'),
('Hulu','not as big as netflix','https://hulu.com','3'),
('Facebook', 'lots of privacy issues','https://facebookc.com','2'),
('Google.com','best search engine','https://google.com','5')

;

